# Generated by Django 3.1.12 on 2025-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
