# Generated by Django 3.1.12 on 2025-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20250227_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
    ]
