# Generated by Django 5.1.6 on 2025-03-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_id_alter_paymentmethod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(max_length=100),
        ),
    ]
