version: '3.8'

services:
  product:
    build: ./product_service
    container_name: product_service
    ports:
      - "1110:1110"
    environment:
      - cart_api=http://cart:1111/api/cart/
      - customer_api=http://customer:8200/customer/
      - product_api=http://product:1110/api/product/
      - order_api=http://order:8100/order/
      - shipment_api=http://shipment:6789/shipment_service/
      - payment_api=http://payment:6800/payment_api/
    depends_on:
      - mongo
    networks:
      - e_commerce
  cart:
    build: ./cart_service
    container_name: cart_service
    ports:
      - "1111:1111"
    environment:
      - cart_api=http://cart:1111/api/cart/
      - customer_api=http://customer:8200/customer/
      - product_api=http://product:1110/api/product/
      - order_api=http://order:8100/order/
      - shipment_api=http://shipment:6789/shipment_service/
      - payment_api=http://payment:6800/payment_api/
    depends_on:
      - product
    networks:
      - e_commerce

  # customer:
  #   build: ./customer_service
  #   container_name: customer_service
  #   ports:
  #     - "8200:8200"
  #   environment:
  #     - cart_api=http://cart:1111/api/cart/
  #     - customer_api=http://customer:8200/customer/
  #     - product_api=http://product:1110/api/product/
  #     - order_api=http://order:8100/order/
  #     - shipment_api=http://shipment:6789/shipment_service/
  #     - payment_api=http://payment:6800/payment_api/
  #   networks:
  #     - e_commerce

  # order:
  #   build: ./order_service
  #   container_name: order_service
  #   ports:
  #     - "8100:8100"
  #   environment:
  #     - cart_api=http://cart:1111/api/cart/
  #     - customer_api=http://customer:8200/customer/
  #     - product_api=http://product:1110/api/product/
  #     - order_api=http://order:8100/order/
  #     - shipment_api=http://shipment:6789/shipment_service/
  #     - payment_api=http://payment:6800/payment_api/
  #   depends_on:
  #     - cart
  #   networks:
  #     - e_commerce

  # payment:
  #   build: ./payment_service
  #   container_name: payment_service
  #   ports:
  #     - "6800:6800"
  #   environment:
  #     - cart_api=http://cart:1111/api/cart/
  #     - customer_api=http://customer:8200/customer/
  #     - product_api=http://product:1110/api/product/
  #     - order_api=http://order:8100/order/
  #     - shipment_api=http://shipment:6789/shipment_service/
  #     - payment_api=http://payment:6800/payment_api/
  #   networks:
  #     - e_commerce
    
  # shipment:
  #   build: ./shipment_service
  #   container_name: shipment_service
  #   ports:
  #     - "6789:6789"
  #   environment:
  #     - cart_api=http://cart:1111/api/cart/
  #     - customer_api=http://customer:8200/customer/
  #     - product_api=http://product:1110/api/product/
  #     - order_api=http://order:8100/order/
  #     - shipment_api=http://shipment:6789/shipment_service/
  #     - payment_api=http://payment:6800/payment_api/
  #   networks:
  #     - e_commerce

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - e_commerce

networks:
  e_commerce:
    driver: bridge