# Generated by Django 5.1.6 on 2025-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(default='Chưa thanh toán', max_length=20),
        ),
    ]
