# Generated by Django 5.1.6 on 2025-03-12 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipment.package'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipment.recipient'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipment.address'),
        ),
    ]
