# Generated by Django 5.1.6 on 2025-03-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_price_alter_order_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_items',
        ),
    ]
