version: '3.8'

services:
  web:
    build: .
    ports:
      - "1110:1110"
    environment:
      - DEBUG=1
      - MONGO_URI=mongodb://mongo:27017/sadproject2mircoserver
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
