# Generated by Django 5.1.6 on 2025-03-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('product_price', models.FloatField()),
                ('product_description', models.CharField(max_length=255)),
            ],
        ),
    ]
